id: P52AC2912
initial_creation_type: input
source_metadata:
  title: Minyak Kunzang Sönam Series
  language: bo
  description: 'Texts by and about Minyak Kunzang Sönam (mi nyag kun bzang bsod nams,
    1823–1905) alias Thubten Chökyi Drakpa (thub bstan chos kyi grags pa) :'
  volume:
    92b7b6dd0b9d4feea867afd451a8c82a:
      title: Overview of the Bodhicaryāvatāra
      parent: Bodhicaryāvatāra
created_at: '2022-03-01T00:49:12.158990'
last_modified_at: '2022-03-01T00:49:12.158993'
statistics:
  total_words: 640
  total_non_words: 40
quality:
  non_words_ratio: 0.06
